# PyTorch

## { parte 1 - tensores? }

In [1]:
import torch

In [2]:
a = torch.tensor([2.0, 2.0, 2.0])
a

tensor([2., 2., 2.])

In [3]:
a * 2

tensor([4., 4., 4.])

mais ou menos como um array do numpy mas nem tanto...

In [4]:
a.requires_grad_(True)
a

tensor([2., 2., 2.], requires_grad=True)

In [5]:
b = 2*a
b

tensor([4., 4., 4.], grad_fn=<MulBackward>)

In [6]:
gradients = torch.tensor([1.0, 2.0, 3.0])
gradients

tensor([1., 2., 3.])

In [7]:
b.backward(gradients)

In [8]:
b

tensor([4., 4., 4.], grad_fn=<MulBackward>)

In [9]:
a

tensor([2., 2., 2.], requires_grad=True)

In [10]:
a.grad

tensor([2., 4., 6.])

convenhamos que a parte mais chata da implementação de uma rede neural é o backpropagation